[2025-03-27 22:36:14,895] ERROR in app: Î´ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ì³£: no such table: voter_ips
Traceback (most recent call last):
  File "C:\Code\vote\.venv\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\app.py", line 97, in vote
    options = [opt.strip() for opt in request.form.getlist('options[]') if opt.strip()]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: voter_ips
[2025-03-27 22:38:56,947] ERROR in app: Î´ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ì³£: no such table: voter_ips
Traceback (most recent call last):
  File "C:\Code\vote\.venv\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\app.py", line 97, in vote
    options = [opt.strip() for opt in request.form.getlist('options[]') if opt.strip()]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: voter_ips
[2025-03-27 22:40:01,474] ERROR in app: Î´ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ì³£: no such table: voter_ips
Traceback (most recent call last):
  File "C:\Code\vote\.venv\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\app.py", line 97, in vote
    # ï¿½ï¿½ï¿½ï¿½Ã»ï¿½ï¿½Ç·ï¿½ï¿½Ñ¾ï¿½Í¶ï¿½ï¿½Æ±
              ^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: voter_ips
[2025-03-27 22:40:15,739] ERROR in app: Î´ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ì³£: no such table: voter_ips
Traceback (most recent call last):
  File "C:\Code\vote\.venv\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\app.py", line 97, in vote
    # ï¿½ï¿½ï¿½ï¿½Ã»ï¿½ï¿½Ç·ï¿½ï¿½Ñ¾ï¿½Í¶ï¿½ï¿½Æ±
              ^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: voter_ips
[2025-03-27 22:40:51,119] ERROR in app: Î´ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ì³£: no such table: voter_ips
Traceback (most recent call last):
  File "C:\Code\vote\.venv\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\app.py", line 97, in vote
    # ï¿½ï¿½ï¿½ï¿½Ã»ï¿½ï¿½Ç·ï¿½ï¿½Ñ¾ï¿½Í¶ï¿½ï¿½Æ±
              ^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: voter_ips
[2025-03-27 22:40:52,659] ERROR in app: Î´ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ì³£: no such table: voter_ips
Traceback (most recent call last):
  File "C:\Code\vote\.venv\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\app.py", line 97, in vote
    # ï¿½ï¿½ï¿½ï¿½Ã»ï¿½ï¿½Ç·ï¿½ï¿½Ñ¾ï¿½Í¶ï¿½ï¿½Æ±
              ^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: voter_ips
[2025-03-27 22:41:17,390] ERROR in app: Î´ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ì³£: no such table: voter_ips
Traceback (most recent call last):
  File "C:\Code\vote\.venv\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\app.py", line 97, in vote
    # ï¿½ï¿½ï¿½ï¿½Ã»ï¿½ï¿½Ç·ï¿½ï¿½Ñ¾ï¿½Í¶ï¿½ï¿½Æ±
              ^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: voter_ips
2025-03-28 10:11:44,005 ERROR: Î´´¦ÀíµÄÒì³£: no such column: browser_fingerprint [in C:\Code\vote\app.py:248]
Traceback (most recent call last):
  File "C:\Code\vote\.venv\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\app.py", line 152, in vote
    last_vote = db.execute('''
                ^^^^^^^^^^^^^^
sqlite3.OperationalError: no such column: browser_fingerprint
2025-03-28 10:12:02,107 ERROR: Î´´¦ÀíµÄÒì³£: no such column: browser_fingerprint [in C:\Code\vote\app.py:248]
Traceback (most recent call last):
  File "C:\Code\vote\.venv\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\app.py", line 152, in vote
    last_vote = db.execute('''
                ^^^^^^^^^^^^^^
sqlite3.OperationalError: no such column: browser_fingerprint
2025-03-28 10:12:06,698 ERROR: Î´´¦ÀíµÄÒì³£: no such column: browser_fingerprint [in C:\Code\vote\app.py:248]
Traceback (most recent call last):
  File "C:\Code\vote\.venv\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\app.py", line 152, in vote
    last_vote = db.execute('''
                ^^^^^^^^^^^^^^
sqlite3.OperationalError: no such column: browser_fingerprint
2025-03-28 11:18:38,790 ERROR: Î´´¦ÀíµÄÒì³£: No module named 'pytz' [in C:\Code\vote\app.py:286]
Traceback (most recent call last):
  File "C:\Code\vote\.venv\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\app.py", line 117, in index
    import pytz
ModuleNotFoundError: No module named 'pytz'
2025-03-28 11:18:42,178 ERROR: Î´´¦ÀíµÄÒì³£: No module named 'pytz' [in C:\Code\vote\app.py:286]
Traceback (most recent call last):
  File "C:\Code\vote\.venv\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\app.py", line 117, in index
    import pytz
ModuleNotFoundError: No module named 'pytz'
2025-03-28 12:39:39,833 ERROR: Î´´¦ÀíµÄÒì³£: Object of type Row is not JSON serializable [in C:\Code\vote\app.py:320]
Traceback (most recent call last):
  File "C:\Code\vote\.venv\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\app.py", line 293, in results
    return render_template('results.html', poll=poll_info, options=options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\flask\templating.py", line 152, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\flask\templating.py", line 133, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "C:\Code\vote\.venv\Lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Code\vote\templates\results.html", line 1, in top-level template code
    {% extends 'base.html' %}
  File "C:\Code\vote\templates\base.html", line 57, in top-level template code
    {% block content %}{% endblock %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\templates\results.html", line 64, in block 'content'
    const options = {{ options|tojson }};
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\jinja2\filters.py", line 1688, in do_tojson
    return htmlsafe_json_dumps(value, dumps=dumps, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\jinja2\utils.py", line 658, in htmlsafe_json_dumps
    dumps(obj, **kwargs)
  File "C:\Code\vote\.venv\Lib\site-packages\flask\json\provider.py", line 180, in dumps
    return json.dumps(obj, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2544.0_x64__qbz5n2kfra8p0\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2544.0_x64__qbz5n2kfra8p0\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2544.0_x64__qbz5n2kfra8p0\Lib\json\encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\flask\json\provider.py", line 120, in _default
    raise TypeError(f"Object of type {type(o).__name__} is not JSON serializable")
TypeError: Object of type Row is not JSON serializable
2025-03-28 12:39:42,080 ERROR: Î´´¦ÀíµÄÒì³£: Object of type Row is not JSON serializable [in C:\Code\vote\app.py:320]
Traceback (most recent call last):
  File "C:\Code\vote\.venv\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\app.py", line 293, in results
    return render_template('results.html', poll=poll_info, options=options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\flask\templating.py", line 152, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\flask\templating.py", line 133, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "C:\Code\vote\.venv\Lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Code\vote\templates\results.html", line 1, in top-level template code
    {% extends 'base.html' %}
  File "C:\Code\vote\templates\base.html", line 57, in top-level template code
    {% block content %}{% endblock %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\templates\results.html", line 64, in block 'content'
    const options = {{ options|tojson }};
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\jinja2\filters.py", line 1688, in do_tojson
    return htmlsafe_json_dumps(value, dumps=dumps, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\jinja2\utils.py", line 658, in htmlsafe_json_dumps
    dumps(obj, **kwargs)
  File "C:\Code\vote\.venv\Lib\site-packages\flask\json\provider.py", line 180, in dumps
    return json.dumps(obj, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2544.0_x64__qbz5n2kfra8p0\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2544.0_x64__qbz5n2kfra8p0\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2544.0_x64__qbz5n2kfra8p0\Lib\json\encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\flask\json\provider.py", line 120, in _default
    raise TypeError(f"Object of type {type(o).__name__} is not JSON serializable")
TypeError: Object of type Row is not JSON serializable
2025-03-28 12:39:42,832 ERROR: Î´´¦ÀíµÄÒì³£: Object of type Row is not JSON serializable [in C:\Code\vote\app.py:320]
Traceback (most recent call last):
  File "C:\Code\vote\.venv\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\app.py", line 293, in results
    return render_template('results.html', poll=poll_info, options=options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\flask\templating.py", line 152, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\flask\templating.py", line 133, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "C:\Code\vote\.venv\Lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Code\vote\templates\results.html", line 1, in top-level template code
    {% extends 'base.html' %}
  File "C:\Code\vote\templates\base.html", line 57, in top-level template code
    {% block content %}{% endblock %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\templates\results.html", line 64, in block 'content'
    const options = {{ options|tojson }};
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\jinja2\filters.py", line 1688, in do_tojson
    return htmlsafe_json_dumps(value, dumps=dumps, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\jinja2\utils.py", line 658, in htmlsafe_json_dumps
    dumps(obj, **kwargs)
  File "C:\Code\vote\.venv\Lib\site-packages\flask\json\provider.py", line 180, in dumps
    return json.dumps(obj, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2544.0_x64__qbz5n2kfra8p0\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2544.0_x64__qbz5n2kfra8p0\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2544.0_x64__qbz5n2kfra8p0\Lib\json\encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\flask\json\provider.py", line 120, in _default
    raise TypeError(f"Object of type {type(o).__name__} is not JSON serializable")
TypeError: Object of type Row is not JSON serializable
2025-03-28 12:40:47,133 ERROR: Î´´¦ÀíµÄÒì³£: Object of type Row is not JSON serializable [in C:\Code\vote\app.py:320]
Traceback (most recent call last):
  File "C:\Code\vote\.venv\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\app.py", line 293, in results
    return render_template('results.html', poll=poll_info, options=options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\flask\templating.py", line 152, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\flask\templating.py", line 133, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "C:\Code\vote\.venv\Lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Code\vote\templates\results.html", line 1, in top-level template code
    {% extends 'base.html' %}
  File "C:\Code\vote\templates\base.html", line 57, in top-level template code
    {% block content %}{% endblock %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\templates\results.html", line 64, in block 'content'
    const options = {{ options|tojson }};
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\jinja2\filters.py", line 1688, in do_tojson
    return htmlsafe_json_dumps(value, dumps=dumps, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\jinja2\utils.py", line 658, in htmlsafe_json_dumps
    dumps(obj, **kwargs)
  File "C:\Code\vote\.venv\Lib\site-packages\flask\json\provider.py", line 180, in dumps
    return json.dumps(obj, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2544.0_x64__qbz5n2kfra8p0\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2544.0_x64__qbz5n2kfra8p0\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2544.0_x64__qbz5n2kfra8p0\Lib\json\encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\flask\json\provider.py", line 120, in _default
    raise TypeError(f"Object of type {type(o).__name__} is not JSON serializable")
TypeError: Object of type Row is not JSON serializable
2025-03-28 12:40:48,181 ERROR: Î´´¦ÀíµÄÒì³£: Object of type Row is not JSON serializable [in C:\Code\vote\app.py:320]
Traceback (most recent call last):
  File "C:\Code\vote\.venv\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\app.py", line 293, in results
    return render_template('results.html', poll=poll_info, options=options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\flask\templating.py", line 152, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\flask\templating.py", line 133, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "C:\Code\vote\.venv\Lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Code\vote\templates\results.html", line 1, in top-level template code
    {% extends 'base.html' %}
  File "C:\Code\vote\templates\base.html", line 57, in top-level template code
    {% block content %}{% endblock %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\templates\results.html", line 64, in block 'content'
    const options = {{ options|tojson }};
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\jinja2\filters.py", line 1688, in do_tojson
    return htmlsafe_json_dumps(value, dumps=dumps, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\jinja2\utils.py", line 658, in htmlsafe_json_dumps
    dumps(obj, **kwargs)
  File "C:\Code\vote\.venv\Lib\site-packages\flask\json\provider.py", line 180, in dumps
    return json.dumps(obj, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2544.0_x64__qbz5n2kfra8p0\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2544.0_x64__qbz5n2kfra8p0\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2544.0_x64__qbz5n2kfra8p0\Lib\json\encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\flask\json\provider.py", line 120, in _default
    raise TypeError(f"Object of type {type(o).__name__} is not JSON serializable")
TypeError: Object of type Row is not JSON serializable
2025-03-28 12:40:48,945 ERROR: Î´´¦ÀíµÄÒì³£: Object of type Row is not JSON serializable [in C:\Code\vote\app.py:320]
Traceback (most recent call last):
  File "C:\Code\vote\.venv\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\app.py", line 293, in results
    return render_template('results.html', poll=poll_info, options=options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\flask\templating.py", line 152, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\flask\templating.py", line 133, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "C:\Code\vote\.venv\Lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Code\vote\templates\results.html", line 1, in top-level template code
    {% extends 'base.html' %}
  File "C:\Code\vote\templates\base.html", line 57, in top-level template code
    {% block content %}{% endblock %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\templates\results.html", line 64, in block 'content'
    const options = {{ options|tojson }};
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\jinja2\filters.py", line 1688, in do_tojson
    return htmlsafe_json_dumps(value, dumps=dumps, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\jinja2\utils.py", line 658, in htmlsafe_json_dumps
    dumps(obj, **kwargs)
  File "C:\Code\vote\.venv\Lib\site-packages\flask\json\provider.py", line 180, in dumps
    return json.dumps(obj, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2544.0_x64__qbz5n2kfra8p0\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2544.0_x64__qbz5n2kfra8p0\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2544.0_x64__qbz5n2kfra8p0\Lib\json\encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\flask\json\provider.py", line 120, in _default
    raise TypeError(f"Object of type {type(o).__name__} is not JSON serializable")
TypeError: Object of type Row is not JSON serializable
2025-03-28 12:40:49,319 ERROR: Î´´¦ÀíµÄÒì³£: Object of type Row is not JSON serializable [in C:\Code\vote\app.py:320]
Traceback (most recent call last):
  File "C:\Code\vote\.venv\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\app.py", line 293, in results
    return render_template('results.html', poll=poll_info, options=options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\flask\templating.py", line 152, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\flask\templating.py", line 133, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "C:\Code\vote\.venv\Lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Code\vote\templates\results.html", line 1, in top-level template code
    {% extends 'base.html' %}
  File "C:\Code\vote\templates\base.html", line 57, in top-level template code
    {% block content %}{% endblock %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\templates\results.html", line 64, in block 'content'
    const options = {{ options|tojson }};
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\jinja2\filters.py", line 1688, in do_tojson
    return htmlsafe_json_dumps(value, dumps=dumps, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\jinja2\utils.py", line 658, in htmlsafe_json_dumps
    dumps(obj, **kwargs)
  File "C:\Code\vote\.venv\Lib\site-packages\flask\json\provider.py", line 180, in dumps
    return json.dumps(obj, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2544.0_x64__qbz5n2kfra8p0\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2544.0_x64__qbz5n2kfra8p0\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2544.0_x64__qbz5n2kfra8p0\Lib\json\encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\flask\json\provider.py", line 120, in _default
    raise TypeError(f"Object of type {type(o).__name__} is not JSON serializable")
TypeError: Object of type Row is not JSON serializable
2025-03-28 12:40:49,461 ERROR: Î´´¦ÀíµÄÒì³£: Object of type Row is not JSON serializable [in C:\Code\vote\app.py:320]
Traceback (most recent call last):
  File "C:\Code\vote\.venv\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\app.py", line 293, in results
    return render_template('results.html', poll=poll_info, options=options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\flask\templating.py", line 152, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\flask\templating.py", line 133, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "C:\Code\vote\.venv\Lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Code\vote\templates\results.html", line 1, in top-level template code
    {% extends 'base.html' %}
  File "C:\Code\vote\templates\base.html", line 57, in top-level template code
    {% block content %}{% endblock %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\templates\results.html", line 64, in block 'content'
    const options = {{ options|tojson }};
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\jinja2\filters.py", line 1688, in do_tojson
    return htmlsafe_json_dumps(value, dumps=dumps, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\jinja2\utils.py", line 658, in htmlsafe_json_dumps
    dumps(obj, **kwargs)
  File "C:\Code\vote\.venv\Lib\site-packages\flask\json\provider.py", line 180, in dumps
    return json.dumps(obj, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2544.0_x64__qbz5n2kfra8p0\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2544.0_x64__qbz5n2kfra8p0\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2544.0_x64__qbz5n2kfra8p0\Lib\json\encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\flask\json\provider.py", line 120, in _default
    raise TypeError(f"Object of type {type(o).__name__} is not JSON serializable")
TypeError: Object of type Row is not JSON serializable
2025-03-28 12:40:54,310 ERROR: Î´´¦ÀíµÄÒì³£: Object of type Row is not JSON serializable [in C:\Code\vote\app.py:320]
Traceback (most recent call last):
  File "C:\Code\vote\.venv\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\app.py", line 293, in results
    return render_template('results.html', poll=poll_info, options=options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\flask\templating.py", line 152, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\flask\templating.py", line 133, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "C:\Code\vote\.venv\Lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Code\vote\templates\results.html", line 1, in top-level template code
    {% extends 'base.html' %}
  File "C:\Code\vote\templates\base.html", line 57, in top-level template code
    {% block content %}{% endblock %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\templates\results.html", line 64, in block 'content'
    const options = {{ options|tojson }};
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\jinja2\filters.py", line 1688, in do_tojson
    return htmlsafe_json_dumps(value, dumps=dumps, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\jinja2\utils.py", line 658, in htmlsafe_json_dumps
    dumps(obj, **kwargs)
  File "C:\Code\vote\.venv\Lib\site-packages\flask\json\provider.py", line 180, in dumps
    return json.dumps(obj, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2544.0_x64__qbz5n2kfra8p0\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2544.0_x64__qbz5n2kfra8p0\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2544.0_x64__qbz5n2kfra8p0\Lib\json\encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\flask\json\provider.py", line 120, in _default
    raise TypeError(f"Object of type {type(o).__name__} is not JSON serializable")
TypeError: Object of type Row is not JSON serializable
2025-03-28 12:41:00,069 ERROR: Î´´¦ÀíµÄÒì³£: Object of type Row is not JSON serializable [in C:\Code\vote\app.py:320]
Traceback (most recent call last):
  File "C:\Code\vote\.venv\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\app.py", line 293, in results
    return render_template('results.html', poll=poll_info, options=options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\flask\templating.py", line 152, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\flask\templating.py", line 133, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "C:\Code\vote\.venv\Lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Code\vote\templates\results.html", line 1, in top-level template code
    {% extends 'base.html' %}
  File "C:\Code\vote\templates\base.html", line 57, in top-level template code
    {% block content %}{% endblock %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\templates\results.html", line 64, in block 'content'
    const options = {{ options|tojson }};
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\jinja2\filters.py", line 1688, in do_tojson
    return htmlsafe_json_dumps(value, dumps=dumps, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\jinja2\utils.py", line 658, in htmlsafe_json_dumps
    dumps(obj, **kwargs)
  File "C:\Code\vote\.venv\Lib\site-packages\flask\json\provider.py", line 180, in dumps
    return json.dumps(obj, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2544.0_x64__qbz5n2kfra8p0\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2544.0_x64__qbz5n2kfra8p0\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2544.0_x64__qbz5n2kfra8p0\Lib\json\encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\flask\json\provider.py", line 120, in _default
    raise TypeError(f"Object of type {type(o).__name__} is not JSON serializable")
TypeError: Object of type Row is not JSON serializable
2025-03-28 12:41:38,154 ERROR: Î´´¦ÀíµÄÒì³£: Object of type Row is not JSON serializable [in C:\Code\vote\app.py:320]
Traceback (most recent call last):
  File "C:\Code\vote\.venv\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\app.py", line 293, in results
    return render_template('results.html', poll=poll_info, options=options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\flask\templating.py", line 152, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\flask\templating.py", line 133, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "C:\Code\vote\.venv\Lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Code\vote\templates\results.html", line 1, in top-level template code
    {% extends 'base.html' %}
  File "C:\Code\vote\templates\base.html", line 57, in top-level template code
    {% block content %}{% endblock %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\templates\results.html", line 64, in block 'content'
    const options = {{ options|tojson }};
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\jinja2\filters.py", line 1688, in do_tojson
    return htmlsafe_json_dumps(value, dumps=dumps, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\jinja2\utils.py", line 658, in htmlsafe_json_dumps
    dumps(obj, **kwargs)
  File "C:\Code\vote\.venv\Lib\site-packages\flask\json\provider.py", line 180, in dumps
    return json.dumps(obj, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2544.0_x64__qbz5n2kfra8p0\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2544.0_x64__qbz5n2kfra8p0\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2544.0_x64__qbz5n2kfra8p0\Lib\json\encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\flask\json\provider.py", line 120, in _default
    raise TypeError(f"Object of type {type(o).__name__} is not JSON serializable")
TypeError: Object of type Row is not JSON serializable
2025-03-28 12:41:38,915 ERROR: Î´´¦ÀíµÄÒì³£: Object of type Row is not JSON serializable [in C:\Code\vote\app.py:320]
Traceback (most recent call last):
  File "C:\Code\vote\.venv\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\app.py", line 293, in results
    return render_template('results.html', poll=poll_info, options=options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\flask\templating.py", line 152, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\flask\templating.py", line 133, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "C:\Code\vote\.venv\Lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Code\vote\templates\results.html", line 1, in top-level template code
    {% extends 'base.html' %}
  File "C:\Code\vote\templates\base.html", line 57, in top-level template code
    {% block content %}{% endblock %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\templates\results.html", line 64, in block 'content'
    const options = {{ options|tojson }};
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\jinja2\filters.py", line 1688, in do_tojson
    return htmlsafe_json_dumps(value, dumps=dumps, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\jinja2\utils.py", line 658, in htmlsafe_json_dumps
    dumps(obj, **kwargs)
  File "C:\Code\vote\.venv\Lib\site-packages\flask\json\provider.py", line 180, in dumps
    return json.dumps(obj, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2544.0_x64__qbz5n2kfra8p0\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2544.0_x64__qbz5n2kfra8p0\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2544.0_x64__qbz5n2kfra8p0\Lib\json\encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\flask\json\provider.py", line 120, in _default
    raise TypeError(f"Object of type {type(o).__name__} is not JSON serializable")
TypeError: Object of type Row is not JSON serializable
2025-03-28 12:41:42,661 ERROR: Î´´¦ÀíµÄÒì³£: Object of type Row is not JSON serializable [in C:\Code\vote\app.py:320]
Traceback (most recent call last):
  File "C:\Code\vote\.venv\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\app.py", line 293, in results
    return render_template('results.html', poll=poll_info, options=options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\flask\templating.py", line 152, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\flask\templating.py", line 133, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "C:\Code\vote\.venv\Lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Code\vote\templates\results.html", line 1, in top-level template code
    {% extends 'base.html' %}
  File "C:\Code\vote\templates\base.html", line 57, in top-level template code
    {% block content %}{% endblock %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\templates\results.html", line 64, in block 'content'
    const options = {{ options|tojson }};
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\jinja2\filters.py", line 1688, in do_tojson
    return htmlsafe_json_dumps(value, dumps=dumps, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\jinja2\utils.py", line 658, in htmlsafe_json_dumps
    dumps(obj, **kwargs)
  File "C:\Code\vote\.venv\Lib\site-packages\flask\json\provider.py", line 180, in dumps
    return json.dumps(obj, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2544.0_x64__qbz5n2kfra8p0\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2544.0_x64__qbz5n2kfra8p0\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2544.0_x64__qbz5n2kfra8p0\Lib\json\encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\flask\json\provider.py", line 120, in _default
    raise TypeError(f"Object of type {type(o).__name__} is not JSON serializable")
TypeError: Object of type Row is not JSON serializable
2025-03-28 12:41:44,892 ERROR: Î´´¦ÀíµÄÒì³£: Object of type Row is not JSON serializable [in C:\Code\vote\app.py:320]
Traceback (most recent call last):
  File "C:\Code\vote\.venv\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\app.py", line 293, in results
    return render_template('results.html', poll=poll_info, options=options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\flask\templating.py", line 152, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\flask\templating.py", line 133, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "C:\Code\vote\.venv\Lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Code\vote\templates\results.html", line 1, in top-level template code
    {% extends 'base.html' %}
  File "C:\Code\vote\templates\base.html", line 57, in top-level template code
    {% block content %}{% endblock %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\templates\results.html", line 64, in block 'content'
    const options = {{ options|tojson }};
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\jinja2\filters.py", line 1688, in do_tojson
    return htmlsafe_json_dumps(value, dumps=dumps, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\jinja2\utils.py", line 658, in htmlsafe_json_dumps
    dumps(obj, **kwargs)
  File "C:\Code\vote\.venv\Lib\site-packages\flask\json\provider.py", line 180, in dumps
    return json.dumps(obj, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2544.0_x64__qbz5n2kfra8p0\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2544.0_x64__qbz5n2kfra8p0\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2544.0_x64__qbz5n2kfra8p0\Lib\json\encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\flask\json\provider.py", line 120, in _default
    raise TypeError(f"Object of type {type(o).__name__} is not JSON serializable")
TypeError: Object of type Row is not JSON serializable
2025-03-28 12:41:46,993 ERROR: Î´´¦ÀíµÄÒì³£: Object of type Row is not JSON serializable [in C:\Code\vote\app.py:320]
Traceback (most recent call last):
  File "C:\Code\vote\.venv\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\app.py", line 293, in results
    return render_template('results.html', poll=poll_info, options=options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\flask\templating.py", line 152, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\flask\templating.py", line 133, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "C:\Code\vote\.venv\Lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Code\vote\templates\results.html", line 1, in top-level template code
    {% extends 'base.html' %}
  File "C:\Code\vote\templates\base.html", line 57, in top-level template code
    {% block content %}{% endblock %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\templates\results.html", line 64, in block 'content'
    const options = {{ options|tojson }};
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\jinja2\filters.py", line 1688, in do_tojson
    return htmlsafe_json_dumps(value, dumps=dumps, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\jinja2\utils.py", line 658, in htmlsafe_json_dumps
    dumps(obj, **kwargs)
  File "C:\Code\vote\.venv\Lib\site-packages\flask\json\provider.py", line 180, in dumps
    return json.dumps(obj, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2544.0_x64__qbz5n2kfra8p0\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2544.0_x64__qbz5n2kfra8p0\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2544.0_x64__qbz5n2kfra8p0\Lib\json\encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\flask\json\provider.py", line 120, in _default
    raise TypeError(f"Object of type {type(o).__name__} is not JSON serializable")
TypeError: Object of type Row is not JSON serializable
2025-03-28 12:42:56,517 ERROR: Î´´¦ÀíµÄÒì³£: Object of type Row is not JSON serializable [in C:\Code\vote\app.py:327]
Traceback (most recent call last):
  File "C:\Code\vote\.venv\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\app.py", line 300, in results
    return render_template('results.html', poll=poll_info, options=options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\flask\templating.py", line 152, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\flask\templating.py", line 133, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "C:\Code\vote\.venv\Lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Code\vote\templates\results.html", line 1, in top-level template code
    {% extends 'base.html' %}
  File "C:\Code\vote\templates\base.html", line 57, in top-level template code
    {% block content %}{% endblock %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\templates\results.html", line 64, in block 'content'
    const options = {{ options|tojson }};
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\jinja2\filters.py", line 1688, in do_tojson
    return htmlsafe_json_dumps(value, dumps=dumps, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\jinja2\utils.py", line 658, in htmlsafe_json_dumps
    dumps(obj, **kwargs)
  File "C:\Code\vote\.venv\Lib\site-packages\flask\json\provider.py", line 180, in dumps
    return json.dumps(obj, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2544.0_x64__qbz5n2kfra8p0\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2544.0_x64__qbz5n2kfra8p0\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2544.0_x64__qbz5n2kfra8p0\Lib\json\encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\flask\json\provider.py", line 120, in _default
    raise TypeError(f"Object of type {type(o).__name__} is not JSON serializable")
TypeError: Object of type Row is not JSON serializable
2025-03-28 12:44:18,346 ERROR: Î´´¦ÀíµÄÒì³£: Object of type Row is not JSON serializable [in C:\Code\vote\app.py:327]
Traceback (most recent call last):
  File "C:\Code\vote\.venv\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\app.py", line 300, in results
    return render_template('results.html', poll=poll_info, options=options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\flask\templating.py", line 152, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\flask\templating.py", line 133, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "C:\Code\vote\.venv\Lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Code\vote\templates\results.html", line 1, in top-level template code
    {% extends 'base.html' %}
  File "C:\Code\vote\templates\base.html", line 57, in top-level template code
    {% block content %}{% endblock %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\templates\results.html", line 64, in block 'content'
    const options = {{ options|tojson }};
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\jinja2\filters.py", line 1688, in do_tojson
    return htmlsafe_json_dumps(value, dumps=dumps, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\jinja2\utils.py", line 658, in htmlsafe_json_dumps
    dumps(obj, **kwargs)
  File "C:\Code\vote\.venv\Lib\site-packages\flask\json\provider.py", line 180, in dumps
    return json.dumps(obj, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2544.0_x64__qbz5n2kfra8p0\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2544.0_x64__qbz5n2kfra8p0\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2544.0_x64__qbz5n2kfra8p0\Lib\json\encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\flask\json\provider.py", line 120, in _default
    raise TypeError(f"Object of type {type(o).__name__} is not JSON serializable")
TypeError: Object of type Row is not JSON serializable
2025-03-28 12:50:44,410 ERROR: Error: name 'convert_to_local_time' is not defined [in C:\Code\vote\app.py:253]
Traceback (most recent call last):
  File "C:\Code\vote\.venv\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\app.py", line 230, in results
    poll_info['created_at'] = convert_to_local_time(poll['created_at'])
                              ^^^^^^^^^^^^^^^^^^^^^
NameError: name 'convert_to_local_time' is not defined
2025-03-28 12:50:53,129 ERROR: Error: name 'convert_to_local_time' is not defined [in C:\Code\vote\app.py:253]
Traceback (most recent call last):
  File "C:\Code\vote\.venv\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\app.py", line 230, in results
    poll_info['created_at'] = convert_to_local_time(poll['created_at'])
                              ^^^^^^^^^^^^^^^^^^^^^
NameError: name 'convert_to_local_time' is not defined
2025-03-28 12:51:02,246 ERROR: Error: name 'get_client_ip' is not defined [in C:\Code\vote\app.py:253]
Traceback (most recent call last):
  File "C:\Code\vote\.venv\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\app.py", line 178, in vote
    ip_address = get_client_ip()
                 ^^^^^^^^^^^^^
NameError: name 'get_client_ip' is not defined
2025-03-28 12:52:41,052 ERROR: Error: name 'get_client_ip' is not defined [in C:\Code\vote\app.py:253]
Traceback (most recent call last):
  File "C:\Code\vote\.venv\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\app.py", line 178, in vote
    ip_address = get_client_ip()
                 ^^^^^^^^^^^^^
NameError: name 'get_client_ip' is not defined
2025-03-28 12:52:43,219 ERROR: Error: name 'convert_to_local_time' is not defined [in C:\Code\vote\app.py:253]
Traceback (most recent call last):
  File "C:\Code\vote\.venv\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\app.py", line 230, in results
    poll_info['created_at'] = convert_to_local_time(poll['created_at'])
                              ^^^^^^^^^^^^^^^^^^^^^
NameError: name 'convert_to_local_time' is not defined
2025-03-28 13:10:22,502 ERROR: Error: 'now' is undefined [in C:\Code\vote\app.py:246]
Traceback (most recent call last):
  File "C:\Code\vote\.venv\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\app.py", line 211, in vote
    return render_template('vote.html', poll=poll, options=options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\flask\templating.py", line 152, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\flask\templating.py", line 133, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "C:\Code\vote\.venv\Lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Code\vote\templates\vote.html", line 1, in top-level template code
    {% extends 'base.html' %}
  File "C:\Code\vote\templates\base.html", line 47, in top-level template code
    <p>&copy; {{ now.year }} Í¶Æ±ÏµÍ³. ±£ÁôËùÓÐÈ¨Àû.</p>
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\jinja2\environment.py", line 485, in getattr
    return getattr(obj, attribute)
           ^^^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.UndefinedError: 'now' is undefined
2025-03-28 13:10:23,667 ERROR: Error: 'now' is undefined [in C:\Code\vote\app.py:246]
Traceback (most recent call last):
  File "C:\Code\vote\.venv\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\app.py", line 211, in vote
    return render_template('vote.html', poll=poll, options=options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\flask\templating.py", line 152, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\flask\templating.py", line 133, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "C:\Code\vote\.venv\Lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Code\vote\templates\vote.html", line 1, in top-level template code
    {% extends 'base.html' %}
  File "C:\Code\vote\templates\base.html", line 47, in top-level template code
    <p>&copy; {{ now.year }} Í¶Æ±ÏµÍ³. ±£ÁôËùÓÐÈ¨Àû.</p>
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\jinja2\environment.py", line 485, in getattr
    return getattr(obj, attribute)
           ^^^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.UndefinedError: 'now' is undefined
2025-03-28 13:11:01,861 ERROR: Error: 'now' is undefined [in C:\Code\vote\app.py:246]
Traceback (most recent call last):
  File "C:\Code\vote\.venv\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\app.py", line 211, in vote
    return render_template('vote.html', poll=poll, options=options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\flask\templating.py", line 152, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\flask\templating.py", line 133, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "C:\Code\vote\.venv\Lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Code\vote\templates\vote.html", line 1, in top-level template code
    {% extends 'base.html' %}
  File "C:\Code\vote\templates\base.html", line 47, in top-level template code
    <p>&copy; {{ now.year }} Í¶Æ±ÏµÍ³. ±£ÁôËùÓÐÈ¨Àû.</p>
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\jinja2\environment.py", line 485, in getattr
    return getattr(obj, attribute)
           ^^^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.UndefinedError: 'now' is undefined
2025-03-28 13:11:02,762 ERROR: Error: 'now' is undefined [in C:\Code\vote\app.py:246]
Traceback (most recent call last):
  File "C:\Code\vote\.venv\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\app.py", line 211, in vote
    return render_template('vote.html', poll=poll, options=options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\flask\templating.py", line 152, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\flask\templating.py", line 133, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "C:\Code\vote\.venv\Lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Code\vote\templates\vote.html", line 1, in top-level template code
    {% extends 'base.html' %}
  File "C:\Code\vote\templates\base.html", line 47, in top-level template code
    <p>&copy; {{ now.year }} Í¶Æ±ÏµÍ³. ±£ÁôËùÓÐÈ¨Àû.</p>
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\jinja2\environment.py", line 485, in getattr
    return getattr(obj, attribute)
           ^^^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.UndefinedError: 'now' is undefined
2025-03-28 13:11:03,503 ERROR: Error: 'now' is undefined [in C:\Code\vote\app.py:246]
Traceback (most recent call last):
  File "C:\Code\vote\.venv\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\app.py", line 211, in vote
    return render_template('vote.html', poll=poll, options=options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\flask\templating.py", line 152, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\flask\templating.py", line 133, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "C:\Code\vote\.venv\Lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Code\vote\templates\vote.html", line 1, in top-level template code
    {% extends 'base.html' %}
  File "C:\Code\vote\templates\base.html", line 47, in top-level template code
    <p>&copy; {{ now.year }} Í¶Æ±ÏµÍ³. ±£ÁôËùÓÐÈ¨Àû.</p>
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\jinja2\environment.py", line 485, in getattr
    return getattr(obj, attribute)
           ^^^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.UndefinedError: 'now' is undefined
2025-03-31 16:16:14,337 ERROR: Error: no such table: captcha_data [in C:\Code\vote\app.py:470]
Traceback (most recent call last):
  File "C:\Code\vote\.venv\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\app.py", line 117, in generate_captcha_api
    img_byte_arr = generate_captcha(verification_token)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\app.py", line 102, in generate_captcha
    store_captcha_data(verification_token, target_pos)
  File "C:\Code\vote\app.py", line 48, in store_captcha_data
    db.execute(
sqlite3.OperationalError: no such table: captcha_data
2025-03-31 16:16:19,979 ERROR: Error: no such table: captcha_data [in C:\Code\vote\app.py:470]
Traceback (most recent call last):
  File "C:\Code\vote\.venv\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\app.py", line 117, in generate_captcha_api
    img_byte_arr = generate_captcha(verification_token)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\app.py", line 102, in generate_captcha
    store_captcha_data(verification_token, target_pos)
  File "C:\Code\vote\app.py", line 48, in store_captcha_data
    db.execute(
sqlite3.OperationalError: no such table: captcha_data
2025-03-31 16:16:23,851 ERROR: Error: no such table: captcha_data [in C:\Code\vote\app.py:470]
Traceback (most recent call last):
  File "C:\Code\vote\.venv\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\app.py", line 117, in generate_captcha_api
    img_byte_arr = generate_captcha(verification_token)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\app.py", line 102, in generate_captcha
    store_captcha_data(verification_token, target_pos)
  File "C:\Code\vote\app.py", line 48, in store_captcha_data
    db.execute(
sqlite3.OperationalError: no such table: captcha_data
2025-03-31 16:16:26,724 ERROR: Error: no such table: captcha_data [in C:\Code\vote\app.py:470]
Traceback (most recent call last):
  File "C:\Code\vote\.venv\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\app.py", line 117, in generate_captcha_api
    img_byte_arr = generate_captcha(verification_token)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\app.py", line 102, in generate_captcha
    store_captcha_data(verification_token, target_pos)
  File "C:\Code\vote\app.py", line 48, in store_captcha_data
    db.execute(
sqlite3.OperationalError: no such table: captcha_data
2025-03-31 16:39:54,278 ERROR: Error: no such table: captcha_data [in C:\Code\vote\app.py:475]
Traceback (most recent call last):
  File "C:\Code\vote\.venv\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\app.py", line 117, in generate_captcha_api
    img_byte_arr = generate_captcha(verification_token)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\app.py", line 102, in generate_captcha
    store_captcha_data(verification_token, target_pos)
  File "C:\Code\vote\app.py", line 48, in store_captcha_data
    db.execute(
sqlite3.OperationalError: no such table: captcha_data
2025-03-31 16:40:00,041 ERROR: Error: no such table: captcha_data [in C:\Code\vote\app.py:475]
Traceback (most recent call last):
  File "C:\Code\vote\.venv\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\app.py", line 117, in generate_captcha_api
    img_byte_arr = generate_captcha(verification_token)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\app.py", line 102, in generate_captcha
    store_captcha_data(verification_token, target_pos)
  File "C:\Code\vote\app.py", line 48, in store_captcha_data
    db.execute(
sqlite3.OperationalError: no such table: captcha_data
2025-03-31 16:54:48,804 ERROR: Error: no such table: captcha_data [in C:\Code\vote\app.py:475]
Traceback (most recent call last):
  File "C:\Code\vote\.venv\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\app.py", line 117, in generate_captcha_api
    img_byte_arr = generate_captcha(verification_token)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\app.py", line 102, in generate_captcha
    store_captcha_data(verification_token, target_pos)
  File "C:\Code\vote\app.py", line 48, in store_captcha_data
    db.execute(
sqlite3.OperationalError: no such table: captcha_data
2025-03-31 16:54:52,082 ERROR: Error: no such table: captcha_data [in C:\Code\vote\app.py:475]
Traceback (most recent call last):
  File "C:\Code\vote\.venv\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\app.py", line 117, in generate_captcha_api
    img_byte_arr = generate_captcha(verification_token)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\app.py", line 102, in generate_captcha
    store_captcha_data(verification_token, target_pos)
  File "C:\Code\vote\app.py", line 48, in store_captcha_data
    db.execute(
sqlite3.OperationalError: no such table: captcha_data
2025-03-31 16:58:37,440 ERROR: Error: no such table: captcha_data [in C:\Code\vote\app.py:475]
Traceback (most recent call last):
  File "C:\Code\vote\.venv\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\app.py", line 117, in generate_captcha_api
    img_byte_arr = generate_captcha(verification_token)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\app.py", line 102, in generate_captcha
    store_captcha_data(verification_token, target_pos)
  File "C:\Code\vote\app.py", line 48, in store_captcha_data
    db.execute(
sqlite3.OperationalError: no such table: captcha_data
2025-03-31 16:58:47,132 ERROR: Error: no such table: captcha_data [in C:\Code\vote\app.py:475]
Traceback (most recent call last):
  File "C:\Code\vote\.venv\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\app.py", line 117, in generate_captcha_api
    img_byte_arr = generate_captcha(verification_token)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\app.py", line 102, in generate_captcha
    store_captcha_data(verification_token, target_pos)
  File "C:\Code\vote\app.py", line 48, in store_captcha_data
    db.execute(
sqlite3.OperationalError: no such table: captcha_data
2025-03-31 16:58:52,082 ERROR: Error: no such table: captcha_data [in C:\Code\vote\app.py:475]
Traceback (most recent call last):
  File "C:\Code\vote\.venv\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\app.py", line 117, in generate_captcha_api
    img_byte_arr = generate_captcha(verification_token)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\app.py", line 102, in generate_captcha
    store_captcha_data(verification_token, target_pos)
  File "C:\Code\vote\app.py", line 48, in store_captcha_data
    db.execute(
sqlite3.OperationalError: no such table: captcha_data
2025-03-31 16:58:59,665 ERROR: Error: no such table: captcha_data [in C:\Code\vote\app.py:475]
Traceback (most recent call last):
  File "C:\Code\vote\.venv\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\app.py", line 117, in generate_captcha_api
    img_byte_arr = generate_captcha(verification_token)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\app.py", line 102, in generate_captcha
    store_captcha_data(verification_token, target_pos)
  File "C:\Code\vote\app.py", line 48, in store_captcha_data
    db.execute(
sqlite3.OperationalError: no such table: captcha_data
2025-03-31 17:09:03,701 ERROR: Error: name 'store_captcha_data' is not defined [in C:\Code\vote\app.py:483]
Traceback (most recent call last):
  File "C:\Code\vote\.venv\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\app.py", line 114, in generate_captcha_api
    img_byte_arr = generate_captcha(verification_token)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\app.py", line 99, in generate_captcha
    store_captcha_data(verification_token, target_pos)
    ^^^^^^^^^^^^^^^^^^
NameError: name 'store_captcha_data' is not defined
2025-03-31 17:09:06,555 ERROR: Error: name 'store_captcha_data' is not defined [in C:\Code\vote\app.py:483]
Traceback (most recent call last):
  File "C:\Code\vote\.venv\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\app.py", line 114, in generate_captcha_api
    img_byte_arr = generate_captcha(verification_token)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\app.py", line 99, in generate_captcha
    store_captcha_data(verification_token, target_pos)
    ^^^^^^^^^^^^^^^^^^
NameError: name 'store_captcha_data' is not defined
2025-03-31 17:09:08,048 ERROR: Error: name 'store_captcha_data' is not defined [in C:\Code\vote\app.py:483]
Traceback (most recent call last):
  File "C:\Code\vote\.venv\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\app.py", line 114, in generate_captcha_api
    img_byte_arr = generate_captcha(verification_token)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\app.py", line 99, in generate_captcha
    store_captcha_data(verification_token, target_pos)
    ^^^^^^^^^^^^^^^^^^
NameError: name 'store_captcha_data' is not defined
2025-03-31 17:09:09,654 ERROR: Error: name 'store_captcha_data' is not defined [in C:\Code\vote\app.py:483]
Traceback (most recent call last):
  File "C:\Code\vote\.venv\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\app.py", line 114, in generate_captcha_api
    img_byte_arr = generate_captcha(verification_token)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\app.py", line 99, in generate_captcha
    store_captcha_data(verification_token, target_pos)
    ^^^^^^^^^^^^^^^^^^
NameError: name 'store_captcha_data' is not defined
2025-03-31 17:09:15,095 ERROR: Error: name 'store_captcha_data' is not defined [in C:\Code\vote\app.py:483]
Traceback (most recent call last):
  File "C:\Code\vote\.venv\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\app.py", line 114, in generate_captcha_api
    img_byte_arr = generate_captcha(verification_token)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\app.py", line 99, in generate_captcha
    store_captcha_data(verification_token, target_pos)
    ^^^^^^^^^^^^^^^^^^
NameError: name 'store_captcha_data' is not defined
2025-03-31 17:09:32,820 ERROR: Error: name 'store_captcha_data' is not defined [in C:\Code\vote\app.py:483]
Traceback (most recent call last):
  File "C:\Code\vote\.venv\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\app.py", line 114, in generate_captcha_api
    img_byte_arr = generate_captcha(verification_token)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\app.py", line 99, in generate_captcha
    store_captcha_data(verification_token, target_pos)
    ^^^^^^^^^^^^^^^^^^
NameError: name 'store_captcha_data' is not defined
2025-03-31 17:15:31,507 ERROR: Error: no such table: captcha_data [in C:\Code\vote\app.py:494]
Traceback (most recent call last):
  File "C:\Code\vote\.venv\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\app.py", line 125, in generate_captcha_api
    img_byte_arr = generate_captcha(verification_token)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\app.py", line 110, in generate_captcha
    store_captcha_data(verification_token, target_pos)
  File "C:\Code\vote\app.py", line 65, in store_captcha_data
    db.execute(
sqlite3.OperationalError: no such table: captcha_data
2025-03-31 17:15:31,760 ERROR: Error: no such table: captcha_data [in C:\Code\vote\app.py:494]
Traceback (most recent call last):
  File "C:\Code\vote\.venv\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\app.py", line 125, in generate_captcha_api
    img_byte_arr = generate_captcha(verification_token)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\app.py", line 110, in generate_captcha
    store_captcha_data(verification_token, target_pos)
  File "C:\Code\vote\app.py", line 65, in store_captcha_data
    db.execute(
sqlite3.OperationalError: no such table: captcha_data
2025-03-31 17:15:35,065 ERROR: Error: no such table: captcha_data [in C:\Code\vote\app.py:494]
Traceback (most recent call last):
  File "C:\Code\vote\.venv\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\app.py", line 125, in generate_captcha_api
    img_byte_arr = generate_captcha(verification_token)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\app.py", line 110, in generate_captcha
    store_captcha_data(verification_token, target_pos)
  File "C:\Code\vote\app.py", line 65, in store_captcha_data
    db.execute(
sqlite3.OperationalError: no such table: captcha_data
2025-03-31 17:21:51,847 ERROR: Error: no such table: captcha_data [in C:\Code\vote\app.py:494]
Traceback (most recent call last):
  File "C:\Code\vote\.venv\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\app.py", line 125, in generate_captcha_api
    img_byte_arr = generate_captcha(verification_token)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\app.py", line 110, in generate_captcha
    store_captcha_data(verification_token, target_pos)
  File "C:\Code\vote\app.py", line 65, in store_captcha_data
    db.execute(
sqlite3.OperationalError: no such table: captcha_data
2025-03-31 17:21:52,399 ERROR: Error: no such table: captcha_data [in C:\Code\vote\app.py:494]
Traceback (most recent call last):
  File "C:\Code\vote\.venv\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\app.py", line 125, in generate_captcha_api
    img_byte_arr = generate_captcha(verification_token)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\app.py", line 110, in generate_captcha
    store_captcha_data(verification_token, target_pos)
  File "C:\Code\vote\app.py", line 65, in store_captcha_data
    db.execute(
sqlite3.OperationalError: no such table: captcha_data
2025-03-31 17:21:55,690 ERROR: Error: no such table: captcha_data [in C:\Code\vote\app.py:494]
Traceback (most recent call last):
  File "C:\Code\vote\.venv\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\app.py", line 125, in generate_captcha_api
    img_byte_arr = generate_captcha(verification_token)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\app.py", line 110, in generate_captcha
    store_captcha_data(verification_token, target_pos)
  File "C:\Code\vote\app.py", line 65, in store_captcha_data
    db.execute(
sqlite3.OperationalError: no such table: captcha_data
2025-03-31 17:23:22,522 ERROR: Error: images do not match [in C:\Code\vote\app.py:505]
Traceback (most recent call last):
  File "C:\Code\vote\.venv\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\app.py", line 136, in generate_captcha_api
    img_byte_arr = generate_captcha(verification_token)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\app.py", line 112, in generate_captcha
    bg.paste(slider.rotate(random.randint(-15, 15), expand=True),
  File "C:\Code\vote\.venv\Lib\site-packages\PIL\Image.py", line 1760, in paste
    self.im.paste(im, box, mask.im)
ValueError: images do not match
2025-03-31 17:23:27,509 ERROR: Error: images do not match [in C:\Code\vote\app.py:505]
Traceback (most recent call last):
  File "C:\Code\vote\.venv\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\app.py", line 136, in generate_captcha_api
    img_byte_arr = generate_captcha(verification_token)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\app.py", line 112, in generate_captcha
    bg.paste(slider.rotate(random.randint(-15, 15), expand=True),
  File "C:\Code\vote\.venv\Lib\site-packages\PIL\Image.py", line 1760, in paste
    self.im.paste(im, box, mask.im)
ValueError: images do not match
2025-03-31 17:23:28,943 ERROR: Error: images do not match [in C:\Code\vote\app.py:505]
Traceback (most recent call last):
  File "C:\Code\vote\.venv\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\app.py", line 136, in generate_captcha_api
    img_byte_arr = generate_captcha(verification_token)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\app.py", line 112, in generate_captcha
    bg.paste(slider.rotate(random.randint(-15, 15), expand=True),
  File "C:\Code\vote\.venv\Lib\site-packages\PIL\Image.py", line 1760, in paste
    self.im.paste(im, box, mask.im)
ValueError: images do not match
2025-03-31 17:23:31,989 ERROR: Error: no such table: captcha_data [in C:\Code\vote\app.py:505]
Traceback (most recent call last):
  File "C:\Code\vote\.venv\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\app.py", line 136, in generate_captcha_api
    img_byte_arr = generate_captcha(verification_token)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\app.py", line 121, in generate_captcha
    store_captcha_data(verification_token, target_pos)
  File "C:\Code\vote\app.py", line 65, in store_captcha_data
    db.execute(
sqlite3.OperationalError: no such table: captcha_data
2025-03-31 17:23:48,072 ERROR: Error: images do not match [in C:\Code\vote\app.py:505]
Traceback (most recent call last):
  File "C:\Code\vote\.venv\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\app.py", line 136, in generate_captcha_api
    img_byte_arr = generate_captcha(verification_token)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\app.py", line 112, in generate_captcha
    bg.paste(slider.rotate(random.randint(-15, 15), expand=True),
  File "C:\Code\vote\.venv\Lib\site-packages\PIL\Image.py", line 1760, in paste
    self.im.paste(im, box, mask.im)
ValueError: images do not match
2025-03-31 17:30:19,611 ERROR: Error: images do not match [in C:\Code\vote\app.py:508]
Traceback (most recent call last):
  File "C:\Code\vote\.venv\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\app.py", line 136, in generate_captcha_api
    img_byte_arr = generate_captcha(verification_token)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\app.py", line 112, in generate_captcha
    bg.paste(slider.rotate(random.randint(-15, 15), expand=True),
  File "C:\Code\vote\.venv\Lib\site-packages\PIL\Image.py", line 1760, in paste
    self.im.paste(im, box, mask.im)
ValueError: images do not match
2025-03-31 17:30:22,086 ERROR: Error: table captcha_data has no column named token [in C:\Code\vote\app.py:508]
Traceback (most recent call last):
  File "C:\Code\vote\.venv\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\app.py", line 136, in generate_captcha_api
    img_byte_arr = generate_captcha(verification_token)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\app.py", line 121, in generate_captcha
    store_captcha_data(verification_token, target_pos)
  File "C:\Code\vote\app.py", line 65, in store_captcha_data
    db.execute(
sqlite3.OperationalError: table captcha_data has no column named token
2025-04-02 09:08:07,691 ERROR: Error: images do not match [in C:\Code\vote\app.py:508]
Traceback (most recent call last):
  File "C:\Code\vote\.venv\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\app.py", line 136, in generate_captcha_api
    img_byte_arr = generate_captcha(verification_token)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\app.py", line 112, in generate_captcha
    bg.paste(slider.rotate(random.randint(-15, 15), expand=True),
  File "C:\Code\vote\.venv\Lib\site-packages\PIL\Image.py", line 1760, in paste
    self.im.paste(im, box, mask.im)
ValueError: images do not match
2025-04-02 09:08:12,032 ERROR: Error: table captcha_data has no column named token [in C:\Code\vote\app.py:508]
Traceback (most recent call last):
  File "C:\Code\vote\.venv\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\app.py", line 136, in generate_captcha_api
    img_byte_arr = generate_captcha(verification_token)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\app.py", line 121, in generate_captcha
    store_captcha_data(verification_token, target_pos)
  File "C:\Code\vote\app.py", line 65, in store_captcha_data
    db.execute(
sqlite3.OperationalError: table captcha_data has no column named token
2025-04-02 09:08:19,542 ERROR: Error: images do not match [in C:\Code\vote\app.py:508]
Traceback (most recent call last):
  File "C:\Code\vote\.venv\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\app.py", line 136, in generate_captcha_api
    img_byte_arr = generate_captcha(verification_token)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\app.py", line 112, in generate_captcha
    bg.paste(slider.rotate(random.randint(-15, 15), expand=True),
  File "C:\Code\vote\.venv\Lib\site-packages\PIL\Image.py", line 1760, in paste
    self.im.paste(im, box, mask.im)
ValueError: images do not match
2025-04-02 09:08:45,282 ERROR: Error: table captcha_data has no column named token [in C:\Code\vote\app.py:508]
Traceback (most recent call last):
  File "C:\Code\vote\.venv\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\app.py", line 136, in generate_captcha_api
    img_byte_arr = generate_captcha(verification_token)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\app.py", line 121, in generate_captcha
    store_captcha_data(verification_token, target_pos)
  File "C:\Code\vote\app.py", line 65, in store_captcha_data
    db.execute(
sqlite3.OperationalError: table captcha_data has no column named token
2025-04-02 09:10:20,730 ERROR: Error: images do not match [in C:\Code\vote\app.py:508]
Traceback (most recent call last):
  File "C:\Code\vote\.venv\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\app.py", line 136, in generate_captcha_api
    img_byte_arr = generate_captcha(verification_token)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\app.py", line 112, in generate_captcha
    bg.paste(slider.rotate(random.randint(-15, 15), expand=True),
  File "C:\Code\vote\.venv\Lib\site-packages\PIL\Image.py", line 1760, in paste
    self.im.paste(im, box, mask.im)
ValueError: images do not match
2025-04-02 09:10:22,364 ERROR: Error: images do not match [in C:\Code\vote\app.py:508]
Traceback (most recent call last):
  File "C:\Code\vote\.venv\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\app.py", line 136, in generate_captcha_api
    img_byte_arr = generate_captcha(verification_token)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\app.py", line 112, in generate_captcha
    bg.paste(slider.rotate(random.randint(-15, 15), expand=True),
  File "C:\Code\vote\.venv\Lib\site-packages\PIL\Image.py", line 1760, in paste
    self.im.paste(im, box, mask.im)
ValueError: images do not match
2025-04-02 09:10:26,931 ERROR: Error: table captcha_data has no column named token [in C:\Code\vote\app.py:508]
Traceback (most recent call last):
  File "C:\Code\vote\.venv\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\app.py", line 136, in generate_captcha_api
    img_byte_arr = generate_captcha(verification_token)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\app.py", line 121, in generate_captcha
    store_captcha_data(verification_token, target_pos)
  File "C:\Code\vote\app.py", line 65, in store_captcha_data
    db.execute(
sqlite3.OperationalError: table captcha_data has no column named token
2025-04-02 09:10:29,988 ERROR: Error: table captcha_data has no column named token [in C:\Code\vote\app.py:508]
Traceback (most recent call last):
  File "C:\Code\vote\.venv\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\app.py", line 136, in generate_captcha_api
    img_byte_arr = generate_captcha(verification_token)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\app.py", line 121, in generate_captcha
    store_captcha_data(verification_token, target_pos)
  File "C:\Code\vote\app.py", line 65, in store_captcha_data
    db.execute(
sqlite3.OperationalError: table captcha_data has no column named token
2025-04-02 09:11:45,117 ERROR: Generate captcha failed: table captcha_data has no column named token [in C:\Code\vote\app.py:156]
Traceback (most recent call last):
  File "C:\Code\vote\app.py", line 137, in generate_captcha_api
    img_byte_arr = generate_captcha(verification_token)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\app.py", line 121, in generate_captcha
    store_captcha_data(verification_token, target_pos)
  File "C:\Code\vote\app.py", line 65, in store_captcha_data
    db.execute(
sqlite3.OperationalError: table captcha_data has no column named token
2025-04-02 09:11:46,305 ERROR: Generate captcha failed: images do not match [in C:\Code\vote\app.py:156]
Traceback (most recent call last):
  File "C:\Code\vote\app.py", line 137, in generate_captcha_api
    img_byte_arr = generate_captcha(verification_token)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\app.py", line 112, in generate_captcha
    bg.paste(slider.rotate(random.randint(-15, 15), expand=True),
  File "C:\Code\vote\.venv\Lib\site-packages\PIL\Image.py", line 1760, in paste
    self.im.paste(im, box, mask.im)
ValueError: images do not match
2025-04-02 09:11:49,524 ERROR: Generate captcha failed: images do not match [in C:\Code\vote\app.py:156]
Traceback (most recent call last):
  File "C:\Code\vote\app.py", line 137, in generate_captcha_api
    img_byte_arr = generate_captcha(verification_token)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\app.py", line 112, in generate_captcha
    bg.paste(slider.rotate(random.randint(-15, 15), expand=True),
  File "C:\Code\vote\.venv\Lib\site-packages\PIL\Image.py", line 1760, in paste
    self.im.paste(im, box, mask.im)
ValueError: images do not match
2025-04-02 09:13:14,261 ERROR: Generate captcha failed: table captcha_data has no column named token [in C:\Code\vote\app.py:157]
Traceback (most recent call last):
  File "C:\Code\vote\app.py", line 138, in generate_captcha_api
    img_byte_arr = generate_captcha(verification_token)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\app.py", line 122, in generate_captcha
    store_captcha_data(verification_token, target_pos)
  File "C:\Code\vote\app.py", line 65, in store_captcha_data
    db.execute(
sqlite3.OperationalError: table captcha_data has no column named token
2025-04-02 09:13:17,709 ERROR: Generate captcha failed: table captcha_data has no column named token [in C:\Code\vote\app.py:157]
Traceback (most recent call last):
  File "C:\Code\vote\app.py", line 138, in generate_captcha_api
    img_byte_arr = generate_captcha(verification_token)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\app.py", line 122, in generate_captcha
    store_captcha_data(verification_token, target_pos)
  File "C:\Code\vote\app.py", line 65, in store_captcha_data
    db.execute(
sqlite3.OperationalError: table captcha_data has no column named token
2025-04-02 09:14:36,961 ERROR: Generate captcha failed: table captcha_data has no column named target_pos [in C:\Code\vote\app.py:160]
Traceback (most recent call last):
  File "C:\Code\vote\app.py", line 141, in generate_captcha_api
    img_byte_arr = generate_captcha(verification_token)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\app.py", line 125, in generate_captcha
    store_captcha_data(verification_token, target_pos)
  File "C:\Code\vote\app.py", line 68, in store_captcha_data
    db.execute(
sqlite3.OperationalError: table captcha_data has no column named target_pos
2025-04-02 09:14:40,705 ERROR: Generate captcha failed: table captcha_data has no column named target_pos [in C:\Code\vote\app.py:160]
Traceback (most recent call last):
  File "C:\Code\vote\app.py", line 141, in generate_captcha_api
    img_byte_arr = generate_captcha(verification_token)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\app.py", line 125, in generate_captcha
    store_captcha_data(verification_token, target_pos)
  File "C:\Code\vote\app.py", line 68, in store_captcha_data
    db.execute(
sqlite3.OperationalError: table captcha_data has no column named target_pos
2025-04-02 09:17:45,576 ERROR: Generate captcha failed: table captcha_data has no column named target_position [in C:\Code\vote\app.py:160]
Traceback (most recent call last):
  File "C:\Code\vote\app.py", line 141, in generate_captcha_api
    img_byte_arr = generate_captcha(verification_token)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\app.py", line 125, in generate_captcha
    store_captcha_data(verification_token, target_position)
  File "C:\Code\vote\app.py", line 68, in store_captcha_data
    db.execute(
sqlite3.OperationalError: table captcha_data has no column named target_position
2025-04-02 09:17:53,925 ERROR: Generate captcha failed: table captcha_data has no column named target_position [in C:\Code\vote\app.py:160]
Traceback (most recent call last):
  File "C:\Code\vote\app.py", line 141, in generate_captcha_api
    img_byte_arr = generate_captcha(verification_token)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\app.py", line 125, in generate_captcha
    store_captcha_data(verification_token, target_position)
  File "C:\Code\vote\app.py", line 68, in store_captcha_data
    db.execute(
sqlite3.OperationalError: table captcha_data has no column named target_position
2025-04-02 09:21:23,332 ERROR: Generate captcha failed: table captcha_data has no column named target_position [in C:\Code\vote\app.py:182]
Traceback (most recent call last):
  File "C:\Code\vote\app.py", line 142, in generate_captcha_api
    img_byte_arr = generate_captcha(verification_token)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\app.py", line 125, in generate_captcha
    store_captcha_data(verification_token, target_position)
  File "C:\Code\vote\app.py", line 68, in store_captcha_data
    db.execute(
sqlite3.OperationalError: table captcha_data has no column named target_position
2025-04-02 09:21:24,892 ERROR: Generate captcha failed: table captcha_data has no column named target_position [in C:\Code\vote\app.py:182]
Traceback (most recent call last):
  File "C:\Code\vote\app.py", line 142, in generate_captcha_api
    img_byte_arr = generate_captcha(verification_token)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\app.py", line 125, in generate_captcha
    store_captcha_data(verification_token, target_position)
  File "C:\Code\vote\app.py", line 68, in store_captcha_data
    db.execute(
sqlite3.OperationalError: table captcha_data has no column named target_position
2025-04-02 09:21:28,014 ERROR: Generate captcha failed: table captcha_data has no column named target_position [in C:\Code\vote\app.py:182]
Traceback (most recent call last):
  File "C:\Code\vote\app.py", line 142, in generate_captcha_api
    img_byte_arr = generate_captcha(verification_token)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\app.py", line 125, in generate_captcha
    store_captcha_data(verification_token, target_position)
  File "C:\Code\vote\app.py", line 68, in store_captcha_data
    db.execute(
sqlite3.OperationalError: table captcha_data has no column named target_position
2025-04-02 09:21:44,811 ERROR: Generate captcha failed: table captcha_data has no column named target_position [in C:\Code\vote\app.py:182]
Traceback (most recent call last):
  File "C:\Code\vote\app.py", line 142, in generate_captcha_api
    img_byte_arr = generate_captcha(verification_token)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\app.py", line 125, in generate_captcha
    store_captcha_data(verification_token, target_position)
  File "C:\Code\vote\app.py", line 68, in store_captcha_data
    db.execute(
sqlite3.OperationalError: table captcha_data has no column named target_position
2025-04-02 09:21:59,333 ERROR: Generate captcha failed: table captcha_data has no column named target_position [in C:\Code\vote\app.py:182]
Traceback (most recent call last):
  File "C:\Code\vote\app.py", line 142, in generate_captcha_api
    img_byte_arr = generate_captcha(verification_token)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\app.py", line 125, in generate_captcha
    store_captcha_data(verification_token, target_position)
  File "C:\Code\vote\app.py", line 68, in store_captcha_data
    db.execute(
sqlite3.OperationalError: table captcha_data has no column named target_position
2025-04-02 09:25:04,760 ERROR: Generate captcha failed: table captcha_data has no column named target_position [in C:\Code\vote\app.py:182]
Traceback (most recent call last):
  File "C:\Code\vote\app.py", line 142, in generate_captcha_api
    img_byte_arr = generate_captcha(verification_token)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\app.py", line 125, in generate_captcha
    store_captcha_data(verification_token, target_position)
  File "C:\Code\vote\app.py", line 68, in store_captcha_data
    db.execute(
sqlite3.OperationalError: table captcha_data has no column named target_position
2025-04-02 09:47:48,060 ERROR: Generate captcha failed: images do not match [in C:\Code\vote\app.py:195]
Traceback (most recent call last):
  File "C:\Code\vote\app.py", line 155, in generate_captcha_api
    img_byte_arr = generate_captcha(verification_token)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\app.py", line 130, in generate_captcha
    bg.paste(rotated_slider, (target_position, 50), rotated_mask)
  File "C:\Code\vote\.venv\Lib\site-packages\PIL\Image.py", line 1760, in paste
    self.im.paste(im, box, mask.im)
ValueError: images do not match
2025-04-02 09:47:53,342 ERROR: Generate captcha failed: images do not match [in C:\Code\vote\app.py:195]
Traceback (most recent call last):
  File "C:\Code\vote\app.py", line 155, in generate_captcha_api
    img_byte_arr = generate_captcha(verification_token)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\app.py", line 130, in generate_captcha
    bg.paste(rotated_slider, (target_position, 50), rotated_mask)
  File "C:\Code\vote\.venv\Lib\site-packages\PIL\Image.py", line 1760, in paste
    self.im.paste(im, box, mask.im)
ValueError: images do not match
2025-04-04 21:23:33,459 ERROR: Error: no such table: captcha_sessions [in C:\Code\vote\app.py:454]
Traceback (most recent call last):
  File "C:\Code\vote\.venv\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\app.py", line 99, in get_captcha
    store_captcha_session(session_id, captcha_text)
  File "C:\Code\vote\app.py", line 61, in store_captcha_session
    db.execute(
sqlite3.OperationalError: no such table: captcha_sessions
2025-04-04 21:30:49,346 ERROR: Error: no such table: captcha_sessions [in C:\Code\vote\app.py:459]
Traceback (most recent call last):
  File "C:\Code\vote\.venv\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\.venv\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\vote\app.py", line 101, in get_captcha
    store_captcha_session(session_id, captcha_text)
  File "C:\Code\vote\app.py", line 63, in store_captcha_session
    db.execute(
sqlite3.OperationalError: no such table: captcha_sessions
